refactor: husky version "^8.0.0

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,5 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-pnpm lint-staged
+echo "Running pre-commit hook"
+pnpm lint-staged || { echo "lint-staged failed"; exit 1; }
